---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gopalsable
spec:
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Gopal-sakjSable
spec:
  memberOf: []
