version: '3.8' # Specifies the Docker Compose file format version

services:
  # Define the web application service
  web:
    image: nginx:latest # Uses the latest Nginx image from Docker Hub
    ports:
      - "80:80" # Maps port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mounts a local Nginx config file
      - ./html:/usr/share/nginx/html # Mounts a local directory for web content
    depends_on:
      - db # Ensures the 'db' service starts before 'web'
    environment:
      # Example environment variables for the web service
      APP_ENV: production
      APP_DEBUG: "false"
    networks:
      - my-app-network # Connects to a custom network

  # Define the database service
  db:
    image: postgres:13 # Uses PostgreSQL version 13
    environment:
      # Essential environment variables for PostgreSQL
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data # Persists database data
    networks:
      - my-app-network # Connects to the same custom network as 'web'

volumes:
  db_data: # Defines a named volume for database persistence

networks:
  my-app-network: # Defines a custom bridge network
    driver: bridge
