---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gopaljsable
spec:
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Gopal-Sable
spec:
  memberOf: []
