# catalog-info.yaml
# Placed in the root of your service's repository or a designated catalog folder

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-dummy-service
  description: A sample service for demonstration purposes
  annotations:
    # Example annotations - useful for linking to external systems
    github.com/project-slug: my-org/my-dummy-service
    backstage.io/techdocs-ref: url:https://github.com/my-org/my-dummy-service
  tags:
    - dummy
    - backend
    - nodejs
  links:
    - url: https://github.com/my-org/my-dummy-service
      title: GitHub Repo
      icon: github
    - url: https://docs.my-dummy-service.com
      title: Documentation
      icon: docs
spec:
  type: service # Type of the component (e.g., service, website, library)
  lifecycle: experimental # Lifecycle stage (e.g., experimental, production, deprecated)
  owner: default/team-a # The team responsible for this service (references a Group entity)
  system: my-dummy-system # The system this service belongs to (references a System entity)
  consumesApis:
    - my-dummy-api # References an API entity that this service consumes
  providesApis:
    - my-dummy-api-v1 # References an API entity that this service provides
  dependsOn:
    - resource:default/my-dummy-database # References a Resource entity this service depends on
